// site/src/components/Tag.vue
<template>
  <div
    class="
      h-7 rounded-full text-white space-x-0 md:space-x-1 font-medium flex items-center justify-center mr-1 md:mr-2 px-2 md:px-4 bg-opacity-80 cursor-pointer hover:bg-opacity-100
    "
    :class="`bg-${color}`"
  >
    <span class="text-sm md:text-base pb-1">
      {{ name }}
    </span>
    <slot />
  </div>
</template>

<script lang="js">
export default {
  props: {
    name: {
      type: String,
      default: '<Tag>'
    },
    color: {
      type: String,
      default: 'red-500'
    }
  }
}
</script>

// libs/ui/atoms/src/Label/Tag.tsx
import { clsx } from 'clsx';

export type TagItem = {
  label: string;
  count?: number;
  onClick?: () => void;
  className?: string | boolean;
  backgroundClass?: string;
  slug?: string;
};

// TODO: add slug for linking to Tag page
export function Tag({ label, count, className, onClick, backgroundClass = 'bg-4' }: TagItem) {
  return (
    <div
      onClick={onClick}
      className={clsx(
        'py-1.5 px-3 rounded-full w-fit capitalize contrast-125 text-1 flex gap-2 items-center text-sm font-semibold cursor-pointer',
        className,
        backgroundClass
      )}
    >
      {/* {backgroundColor && <div className="w-2 h-2" style={{ backgroundColor }} />} */}
      <span>{label}</span>
      {count ? <span className="text-2 text-3-hover">{count}</span> : null}
    </div>
  );
}
